const VERSION='4.0.0';
const DB_NAME='garethTrainingV3'; // deliberately preserved so v3 data survives an in-place upgrade
const STORE_NAMES=['settings','goals','phases','exercises','templates','planned','workouts','daily','activities','weeklyReviews','aiReviews','exceptions'];
const GOALS=[{id:'lescarroz',name:'Les Carroz',date:'2027-01-09'},{id:'flaine',name:'Flaine',date:'2027-03-27'}];
const PHASES=[
  {id:'reentry',name:'Re-entry',from:'2026-08-24',to:'2026-09-06',summary:'Rebuild the routine without chasing fatigue.',rules:['2 strength sessions','Established lifts: 2 work sets','Rehab: 3 sets','BSS + slow step-down: 2 sets','3–4 RIR initially','1 Snozone + 2 aerobic sessions']},
  {id:'strength',name:'Strength rebuild',from:'2026-09-07',to:'2026-10-18',summary:'Return established work toward normal volume and progress performance.',rules:['Established movements move toward 3 work sets','BSS + step-down stay at 2 initially','Progress reps/load before adding volume','Weekly Snozone','Weight loss stays a priority']},
  {id:'control',name:'Ski strength & control',from:'2026-10-19',to:'2026-11-29',summary:'Keep full-body strength while adding unilateral, eccentric and lateral control.',rules:['Maintain main strength','Progress BSS and step-down quality','Introduce lateral work by substitution','Do not endlessly add lower-body volume']},
  {id:'conditioning',name:'Ski conditioning',from:'2026-11-30',to:'2026-12-20',summary:'Keep controlled technique as fatigue builds.',rules:['Maintain strength','Small endurance dose','Longer/continuous Snozone work','Power is optional']},
  {id:'xmas',name:'Christmas flexibility',from:'2026-12-21',to:'2027-01-01',summary:'Maintain rather than forcing perfect dieting or training.',rules:['Projection assumes maintenance','Train when practical','No compensation','Keep moving']},
  {id:'taper',name:'Les Carroz taper',from:'2027-01-02',to:'2027-01-08',summary:'Reduce fatigue and arrive fresh.',rules:['Reduce lower-body volume','Easy final snow session','No leg-destroying finishers']},
  {id:'trip1',name:'Les Carroz',from:'2027-01-09',to:'2027-01-16',summary:'Ski, enjoy it, and notice what actually limits you.',rules:['Capture useful ski notes','No need to chase gym work']},
  {id:'assess',name:'Recover & assess',from:'2027-01-17',to:'2027-01-31',summary:'Use January to decide what Flaine preparation really needs.',rules:['Recover','Review the trip','Update the programme from evidence']},
  {id:'flainebuild',name:'Flaine build',from:'2027-02-01',to:'2027-03-19',summary:'Build the qualities January exposed.',rules:['Specific emphasis deliberately decided after Les Carroz','Keep strength and snow practice useful']},
  {id:'flaineTaper',name:'Flaine taper',from:'2027-03-20',to:'2027-03-26',summary:'Reduce fatigue and arrive sharp.',rules:['Keep technique','Cut unnecessary fatigue']},
  {id:'trip2',name:'Flaine',from:'2027-03-27',to:'2027-04-03',summary:'Second ski block.',rules:['Enjoy the difference from January']}
];

const state={tab:'today',selectedDate:null,weekOffset:0,activeWorkout:null,openExercise:0,timer:null,timerInterval:null};
const $=s=>document.querySelector(s), $$=s=>[...document.querySelectorAll(s)];
const esc=s=>String(s??'').replace(/[&<>"']/g,m=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}[m]));
const pad=n=>String(n).padStart(2,'0');
const isoDate=(d=new Date())=>`${d.getFullYear()}-${pad(d.getMonth()+1)}-${pad(d.getDate())}`;
const parseDate=s=>new Date(`${s}T12:00:00`);
const fmt=s=>parseDate(s).toLocaleDateString('en-GB',{day:'numeric',month:'short'});
const monday=(d=new Date())=>{let x=new Date(d);x.setHours(12,0,0,0);x.setDate(x.getDate()-((x.getDay()+6)%7));return x};
const addDays=(d,n)=>{let x=new Date(d);x.setDate(x.getDate()+n);return x};
const avg=a=>a.length?a.reduce((x,y)=>x+y,0)/a.length:null;
const num=v=>v===''||v==null?null:Number(v);
const uid=()=>crypto.randomUUID?.()||Math.random().toString(36).slice(2)+Date.now();
const daysUntil=s=>Math.ceil((parseDate(s)-new Date())/86400000);

class DB{
  async init(){this.db=await new Promise((res,rej)=>{const r=indexedDB.open(DB_NAME,1);r.onupgradeneeded=()=>{const d=r.result;STORE_NAMES.forEach(name=>{if(!d.objectStoreNames.contains(name))d.createObjectStore(name,{keyPath:'id',autoIncrement:true})})};r.onsuccess=()=>res(r.result);r.onerror=()=>rej(r.error)})}
  store(n,m='readonly'){return this.db.transaction(n,m).objectStore(n)}
  all(n){return new Promise((res,rej)=>{const r=this.store(n).getAll();r.onsuccess=()=>res(r.result);r.onerror=()=>rej(r.error)})}
  get(n,id){return new Promise((res,rej)=>{const r=this.store(n).get(id);r.onsuccess=()=>res(r.result);r.onerror=()=>rej(r.error)})}
  add(n,o){return new Promise((res,rej)=>{const r=this.store(n,'readwrite').add(o);r.onsuccess=()=>res(r.result);r.onerror=()=>rej(r.error)})}
  put(n,o){return new Promise((res,rej)=>{const r=this.store(n,'readwrite').put(o);r.onsuccess=()=>res(r.result);r.onerror=()=>rej(r.error)})}
  del(n,id){return new Promise((res,rej)=>{const r=this.store(n,'readwrite').delete(id);r.onsuccess=()=>res();r.onerror=()=>rej(r.error)})}
  clear(n){return new Promise((res,rej)=>{const r=this.store(n,'readwrite').clear();r.onsuccess=()=>res();r.onerror=()=>rej(r.error)})}
}
const db=new DB();

async function getSettings(){return (await db.all('settings'))[0]||{}}
async function saveSettings(p){const s=await getSettings();await db.put('settings',{...s,...p,id:s.id||1})}
async function seed(){
  if(!(await db.all('goals')).length)for(const x of GOALS)await db.add('goals',x);
  if(!(await db.all('phases')).length)for(const x of PHASES)await db.add('phases',x);
  let s=await getSettings();
  if(!s.id)await db.add('settings',{heightCm:178,birthDate:'1995-12-11',sex:'male',calorieLow:2150,calorieHigh:2300,externalCalories:2229,proteinFloor:120,proteinPreferred:140,externalProtein:112,stepTarget:8500,aiModel:'gpt-5.6',coachMemory:{themes:['Rebuilding consistency after time away'],testing:[],decisions:['Keep the programme full-body while ski specificity rises gradually'],watch:[]}});
  else if(!s.coachMemory)await saveSettings({coachMemory:{themes:['Rebuilding consistency after time away'],testing:[],decisions:['Keep the programme full-body while ski specificity rises gradually'],watch:[]}});
  // Repair/refresh phase dates from the spec while preserving generated numeric ids.
  const phases=await db.all('phases');
  for(const p of PHASES){const existing=phases.find(x=>x.id===p.id||x.name===p.name);if(existing)await db.put('phases',{...existing,...p});}
  if(!(await db.all('exceptions')).length)await db.add('exceptions',{name:'Christmas flexibility',from:'2026-12-21',to:'2027-01-01',projectionMode:'maintenance',excludeTDEE:true});
  if(!(await db.all('exercises')).length)await seedTraining();
}
async function seedTraining(){
  const exs=[['Hack Squat','Lower body','Machine','kg',5,120],['Pull Up','Back','Bodyweight','bodyweight',1,120],['Chest Fly','Chest','Machine','kg',5,90],['Bulgarian Split Squat','Lower body','Free weight','kg',2.5,120],['Lateral Raise (Machine)','Shoulders','Machine','kg',2.5,90],['Loaded Inversions','Rehab','Cable/other','kg',2.5,90],['Standing Calf Raise (Machine)','Calves','Machine','kg',5,90],['Back Extension','Posterior chain','Bodyweight/plate','kg',5,90],['Bicep Curl (Dumbbell)','Arms','Dumbbell','kg',2.5,90],['Seated Leg Curl (Machine)','Hamstrings','Machine','kg',5,90],['Seated Row (Machine)','Back','Machine','kg',5,90],['Incline Chest Press (Machine)','Chest','Machine','kg',5,90],['Slow Step-down','Lower body','Bodyweight/plate','kg',2.5,90],['Seated Calf Raise (Plate Loaded)','Calves','Plate loaded','kg',5,90],['Triceps Pushdown (Cable - Straight Bar)','Arms','Cable','kg',3,60],['Knee Raise (Captain\'s Chair)','Core','Bodyweight','bodyweight',1,90],['Lateral Lunge','Lower body','Bodyweight/DB','kg',2.5,90]];
  const ids={};for(const [name,category,equipment,loadType,increment,defaultRest] of exs)ids[name]=await db.add('exercises',{name,category,equipment,loadType,increment,defaultRest,notes:''});
  const it=(exerciseId,sets,repMin,repMax,target,rest,startWeight,eventualSets,optional=false,rehab=false,note='')=>({exerciseId,sets,repMin,repMax,target,rest,startWeight,eventualSets,optional,rehab,note,warmups:[],progression:'double'});
  await db.add('templates',{name:'Ski A',type:'strength',description:'Full body · squat + unilateral bias',items:[it(ids['Hack Squat'],2,6,10,6,120,42.5,3),it(ids['Pull Up'],2,4,8,6,120,0,3),it(ids['Chest Fly'],2,8,12,8,90,67.5,3),it(ids['Bulgarian Split Squat'],2,8,10,8,120,0,2,false,false,'Single-leg ski bias. Quality before load.'),it(ids['Lateral Raise (Machine)'],2,8,15,12,90,30,3),it(ids['Loaded Inversions'],3,10,15,12,90,27.5,3,false,true),it(ids['Standing Calf Raise (Machine)'],3,8,15,8,90,52.5,3,false,true),it(ids['Back Extension'],2,8,12,12,90,0,3),it(ids['Bicep Curl (Dumbbell)'],2,8,12,12,90,10,3,true)]});
  await db.add('templates',{name:'Ski B',type:'strength',description:'Full body · hamstrings + eccentric bias',items:[it(ids['Seated Leg Curl (Machine)'],2,6,10,8,90,47.5,3),it(ids['Seated Row (Machine)'],2,8,12,8,90,42.5,3),it(ids['Incline Chest Press (Machine)'],2,8,12,8,90,75,3),it(ids['Slow Step-down'],2,8,10,8,90,0,2,false,false,'3–4 sec lowering. Control, not punishment.'),it(ids['Lateral Raise (Machine)'],2,8,15,12,90,30,3),it(ids['Loaded Inversions'],3,10,15,12,90,27.5,3,false,true),it(ids['Seated Calf Raise (Plate Loaded)'],3,8,15,12,90,47.5,3,false,true),it(ids['Triceps Pushdown (Cable - Straight Bar)'],2,8,12,8,60,47.5,3),it(ids['Knee Raise (Captain\'s Chair)'],2,10,15,15,90,0,3)]});
  await db.add('templates',{name:'Easy cardio',type:'cardio',description:'40–60 min easy aerobic work',activity:{kind:'Easy / Zone 2',minutes:45}});
  await db.add('templates',{name:'Snozone technique',type:'snow',description:'Technique-first indoor ski session',activity:{minutes:60,focus:''}});
}

function currentPhase(phases){
  const sorted=[...phases].filter(p=>p.from&&p.to).sort((a,b)=>a.from.localeCompare(b.from));
  const d=isoDate();
  return sorted.find(p=>d>=p.from&&d<=p.to)|| (d<sorted[0]?.from?sorted[0]:sorted.at(-1));
}
function iconFor(kind,title=''){if(kind==='strength'||/ski a|ski b/i.test(title))return'🏋️';if(kind==='snow'||/snozone/i.test(title))return'⛷️';if(kind==='cardio')return'♥';return'•'}
function toast(msg){const t=$('#toast');t.textContent=msg;t.classList.add('show');clearTimeout(t._x);t._x=setTimeout(()=>t.classList.remove('show'),1800)}
function selectOnFocus(el){el.addEventListener('focus',()=>setTimeout(()=>el.select?.(),0));}
function showSheet(html,{full=false}={}){document.body.style.overflow='hidden';$('#overlay').innerHTML=`<div class="sheetback" id="sheetback"><section class="sheet ${full?'full':''}"><div class="sheet-handle"></div>${html}</section></div>`;$('#sheetback').onclick=e=>{if(e.target.id==='sheetback')closeSheet()};$$('[data-close]').forEach(b=>b.onclick=closeSheet);$$('input[type=number],input[inputmode=numeric],input[inputmode=decimal]').forEach(selectOnFocus)}
function closeSheet(){document.body.style.overflow='';$('#overlay').innerHTML=''}

function renderNav(){const tabs=[['today','⌂','Today'],['week','▦','Week'],['coach','✦','Coach'],['progress','↗','Progress'],['more','•••','More']];$('#nav').innerHTML=tabs.map(([id,ic,l])=>`<button class="navbtn ${state.tab===id?'on':''}" data-nav="${id}"><b>${ic}</b>${l}</button>`).join('');$$('[data-nav]').forEach(b=>b.onclick=()=>{state.tab=b.dataset.nav;render()})}
async function render(){renderNav();clearInterval(state.timerInterval);if(state.tab==='today')await renderToday();if(state.tab==='week')await renderWeek();if(state.tab==='coach')await renderCoach();if(state.tab==='progress')await renderProgress();if(state.tab==='more')await renderMore()}

async function dailyByDate(date){return (await db.all('daily')).find(x=>x.date===date)||null}
async function renderToday(){
  const [goals,phases,planned]=await Promise.all([db.all('goals'),db.all('phases'),db.all('planned')]);const date=isoDate(),day=await dailyByDate(date),phase=currentPhase(phases);const todayPlans=planned.filter(p=>p.date===date);const sortedGoals=[...goals].sort((a,b)=>a.date.localeCompare(b.date));
  $('#app').innerHTML=`<div class="top"><div><div class="eyebrow">Slope</div><h1>Today</h1><div class="muted small">${new Date().toLocaleDateString('en-GB',{weekday:'long',day:'numeric',month:'long'})}</div></div><span class="pill blue">${esc(phase.name)}</span></div>
  <section class="hero"><div class="eyebrow">Next mountain</div><div class="count">${Math.max(0,daysUntil(sortedGoals[0].date))} <span>days to ${esc(sortedGoals[0].name)}</span></div><p class="small muted" style="max-width:70%;margin-bottom:0">${esc(phase.summary)}</p></section>
  <div class="section"><div><h2>Today</h2><p class="small muted">Do the useful thing. Move the rest.</p></div><button class="btn small secondary" id="planToday">+ Plan</button></div>
  ${state.activeWorkout?`<section class="card" style="background:var(--blue-soft);border-color:#ccd9ed"><div class="row"><div><div class="eyebrow">Workout in progress</div><h3 style="margin-top:4px">${esc(state.activeWorkout.templateName)}</h3><div class="small muted">Saved on this device if you close the app.</div></div><button class="btn small blue" id="resumeWorkout">Resume</button></div></section>`:''}${todayPlans.length?todayPlans.map(sessionCard).join(''):`<section class="card empty"><span class="skrimp">🦐</span>Nothing planned. A suspiciously relaxed Skrimp.</section>`}
  <div class="section"><div><h2>Quick log</h2><p class="small muted">Tap a number. No form-filling ceremony.</p></div></div>
  <section class="quick-grid">
    ${quickTile('Weight',day?.weight,'kg','weight')}${quickTile('Calories',day?.calories,'kcal','calories')}${quickTile('Protein',day?.protein,'g','protein')}${quickTile('Steps',day?.steps,'','steps')}
  </section>
  <section class="card" style="margin-top:12px"><div class="row"><div><h3>${day?.note?'Today’s note':'Anything worth remembering?'}</h3><div class="small muted" style="margin-top:4px">${day?.note?esc(day.note):'Only add context if future-you or Coach would care.'}</div></div><button class="btn small ghost" id="noteToday">${day?.note?'Edit':'Add note'}</button></div></section>
  <section class="card"><div class="row"><div><div class="eyebrow">Second marker</div><h3 style="margin-top:4px">Flaine</h3></div><strong>${Math.max(0,daysUntil(sortedGoals[1].date))} days</strong></div></section>`;
  $('#planToday').onclick=()=>openPlan(date);$('#noteToday').onclick=()=>editDailyNote(date);$('#resumeWorkout')?.addEventListener('click',()=>renderWorkout());$$('[data-metric]').forEach(b=>b.onclick=()=>editMetric(date,b.dataset.metric));$$('[data-plan-action]').forEach(bindSessionButton);
}
function quickTile(label,value,unit,key){return `<button class="quick" data-metric="${key}" style="text-align:left;border:1px solid #e3dbce"><span class="label">${label}</span><strong class="${value==null?'metric-empty':''}">${value==null?'—':Number(value).toLocaleString()} ${value!=null?`<span class="unit">${unit}</span>`:''}</strong></button>`}
function sessionCard(p){return `<section class="card"><div class="session"><div class="session-icon">${iconFor(p.kind,p.title)}</div><div class="session-main"><h3>${esc(p.title)}</h3><div class="small muted">${p.status==='done'?'Done':p.status==='skipped'?`Skipped${p.skipReason?' · '+esc(p.skipReason):''}`:(p.note?esc(p.note):'Planned')}</div></div><button class="checkbtn ${p.status==='done'?'done':''}" data-plan-action="toggle" data-id="${p.id}">${p.status==='done'?'✓':'○'}</button></div><div class="wrap" style="margin-top:10px"><button class="btn small blue" data-plan-action="start" data-id="${p.id}">Start</button><button class="btn small ghost" data-plan-action="move" data-id="${p.id}">Move</button><button class="btn small ghost" data-plan-action="edit" data-id="${p.id}">•••</button></div></section>`}
async function editMetric(date,key){const d=await dailyByDate(date),cfg={weight:['Weight','kg','decimal'],calories:['Calories','kcal','numeric'],protein:['Protein','g','numeric'],steps:['Steps','','numeric']}[key];showSheet(`<div class="sheethead"><div><div class="eyebrow">Quick log</div><h2>${cfg[0]}</h2></div><button class="btn small ghost" data-close>Done</button></div><div class="field"><label>${cfg[0]}</label><div class="input-wrap"><input id="metricValue" inputmode="${cfg[2]}" value="${d?.[key]??''}" placeholder="${key==='weight'?'102.5':''}"><span class="suffix">${cfg[1]}</span></div></div><button class="btn blue block" id="saveMetric">Save</button>`);const inp=$('#metricValue');selectOnFocus(inp);setTimeout(()=>inp.focus(),180);$('#saveMetric').onclick=async()=>{const existing=await dailyByDate(date);const obj=existing||{date,weight:null,calories:null,protein:null,steps:null,note:''};obj[key]=num(inp.value);existing?await db.put('daily',obj):await db.add('daily',obj);closeSheet();toast('Saved');render()}}
async function editDailyNote(date){const d=await dailyByDate(date);showSheet(`<div class="sheethead"><div><div class="eyebrow">Context</div><h2>Today’s note</h2></div><button class="btn small ghost" data-close>Close</button></div><p class="small muted">This is automatically available to Coach later. You won’t be asked to repeat it.</p><textarea id="dailyNote" placeholder="Work was mental, hunger was wild, ankle felt surprisingly good…">${esc(d?.note||'')}</textarea><button class="btn blue block" id="saveNote" style="margin-top:12px">Save note</button>`);$('#saveNote').onclick=async()=>{const existing=await dailyByDate(date);const obj=existing||{date,weight:null,calories:null,protein:null,steps:null,note:''};obj.note=$('#dailyNote').value.trim();existing?await db.put('daily',obj):await db.add('daily',obj);closeSheet();render()}}

async function renderWeek(){
  const ws=addDays(monday(),state.weekOffset*7);const days=[0,1,2,3,4,5,6].map(i=>addDays(ws,i));if(!state.selectedDate||state.selectedDate<isoDate(days[0])||state.selectedDate>isoDate(days[6]))state.selectedDate=isoDate(state.weekOffset===0?new Date():days[0]);const plans=(await db.all('planned')).filter(p=>p.date>=isoDate(days[0])&&p.date<=isoDate(days[6]));const sel=plans.filter(p=>p.date===state.selectedDate);const stats=await weekStats(ws);
  $('#app').innerHTML=`<div class="top"><div><div class="eyebrow">Plan reality, not perfection</div><h1>Week</h1><div class="muted small">${fmt(isoDate(days[0]))} – ${fmt(isoDate(days[6]))}</div></div><div class="wrap"><button class="btn small ghost" id="prevWeek">←</button><button class="btn small ghost" id="nextWeek">→</button></div></div>
  <div class="daystrip">${days.map(d=>{const ds=isoDate(d);return `<button class="daychip ${ds===state.selectedDate?'on':''} ${plans.some(p=>p.date===ds)?'has':''}" data-day="${ds}"><div class="dn">${d.toLocaleDateString('en-GB',{weekday:'short'})}</div><div class="dd">${d.getDate()}</div></button>`}).join('')}</div>
  <div class="section"><div><h2>${parseDate(state.selectedDate).toLocaleDateString('en-GB',{weekday:'long'})}</h2><p class="small muted">${fmt(state.selectedDate)}</p></div><button class="btn small secondary" id="addSelected">+ session</button></div>
  <div class="timeline">${sel.length?sel.map(p=>`<div class="event ${p.status==='done'?'done':p.status==='skipped'?'skip':''}"><div class="event-card"><div class="session"><div class="session-icon" style="width:40px;height:40px">${iconFor(p.kind,p.title)}</div><div class="session-main"><h3>${esc(p.title)}</h3><div class="small muted">${p.status||'planned'}</div></div><button class="checkbtn ${p.status==='done'?'done':''}" data-plan-action="toggle" data-id="${p.id}">${p.status==='done'?'✓':'○'}</button></div><div class="wrap" style="margin-top:8px"><button class="btn small blue" data-plan-action="start" data-id="${p.id}">Start</button><button class="btn small ghost" data-plan-action="move" data-id="${p.id}">Move</button><button class="btn small ghost" data-plan-action="edit" data-id="${p.id}">•••</button></div></div></div>`).join(''):`<div class="empty"><span class="skrimp">🦐</span>Clear day. Add something or enjoy the gap.</div>`}</div>
  <div class="section"><div><h2>This week</h2><p class="small muted">${stats.completedPlans}/${stats.planned||5} planned sessions closed</p></div><button class="btn small ghost" id="coachCheck">Coach check-in</button></div>
  <section class="card"><div class="metric-row"><span>Strength</span><strong>${stats.strength}/2</strong></div><div class="metric-row"><span>Snow</span><strong>${stats.snow}/1</strong></div><div class="metric-row"><span>Cardio</span><strong>${stats.cardio}/2</strong></div><div class="progressbar"><div style="width:${Math.min(100,stats.completedPlans/Math.max(1,stats.planned||5)*100)}%"></div></div></section>`;
  $('#prevWeek').onclick=()=>{state.weekOffset--;state.selectedDate=null;render()};$('#nextWeek').onclick=()=>{state.weekOffset++;state.selectedDate=null;render()};$('#addSelected').onclick=()=>openPlan(state.selectedDate);$('#coachCheck').onclick=()=>{state.tab='coach';render();setTimeout(()=>startWeeklyCheckIn(isoDate(ws)),100)};$$('[data-day]').forEach(b=>b.onclick=()=>{state.selectedDate=b.dataset.day;render()});$$('[data-plan-action]').forEach(bindSessionButton);
}
async function weekStats(ws){const a=isoDate(ws),b=isoDate(addDays(ws,6));const [planned,workouts,acts]=await Promise.all([db.all('planned'),db.all('workouts'),db.all('activities')]);const ps=planned.filter(x=>x.date>=a&&x.date<=b),w=workouts.filter(x=>x.date>=a&&x.date<=b),aa=acts.filter(x=>x.date>=a&&x.date<=b);const done=ps.filter(x=>x.status==='done');const strength=Math.max(w.length,done.filter(x=>x.kind==='strength').length),snow=Math.max(aa.filter(x=>x.kind==='snow').length,done.filter(x=>x.kind==='snow').length),cardio=Math.max(aa.filter(x=>x.kind==='cardio').length,done.filter(x=>x.kind==='cardio').length);return{planned:ps.length,completedPlans:done.length,strength,snow,cardio}}
async function bindSessionButton(b){b.onclick=async()=>{const p=await db.get('planned',Number(b.dataset.id)),a=b.dataset.planAction;if(a==='toggle'){p.status=p.status==='done'?'planned':'done';await db.put('planned',p);render()}if(a==='start')await startPlanned(p);if(a==='move')moveSession(p);if(a==='edit')editPlanMenu(p)}}
async function moveSession(p){showSheet(`<div class="sheethead"><div><div class="eyebrow">Move</div><h2>${esc(p.title)}</h2></div><button class="btn small ghost" data-close>Close</button></div><div class="field"><label>New date</label><input id="moveDate" type="date" value="${p.date}"></div><button class="btn blue block" id="saveMove">Move session</button>`);$('#saveMove').onclick=async()=>{p.date=$('#moveDate').value;await db.put('planned',p);closeSheet();toast('Moved');render()}}
async function editPlanMenu(p){showSheet(`<div class="sheethead"><div><div class="eyebrow">Session</div><h2>${esc(p.title)}</h2></div><button class="btn small ghost" data-close>Close</button></div><div class="wrap"><button class="btn secondary" id="editPlan">Edit</button><button class="btn secondary" id="skipPlan">Skip</button><button class="btn danger" id="deletePlan">Delete</button></div>`);$('#editPlan').onclick=()=>openPlan(p.date,p);$('#skipPlan').onclick=async()=>{const reason=prompt("Reason? Recovery / pain / illness / life / couldn't be arsed / other")||'';p.status='skipped';p.skipReason=reason;await db.put('planned',p);closeSheet();render()};$('#deletePlan').onclick=async()=>{if(confirm('Delete this planned session?')){await db.del('planned',p.id);closeSheet();render()}}}
async function openPlan(date,existing=null){const templates=await db.all('templates');showSheet(`<div class="sheethead"><div><div class="eyebrow">${existing?'Edit':'Plan'}</div><h2>${existing?'Session':'Add session'}</h2></div><button class="btn small ghost" data-close>Close</button></div><div class="field"><label>Date</label><input id="pDate" type="date" value="${existing?.date||date}"></div><div class="field"><label>Template</label><select id="pTemplate"><option value="">Simple/custom</option>${templates.map(t=>`<option value="${t.id}" ${existing?.templateId===t.id?'selected':''}>${esc(t.name)}</option>`).join('')}</select></div><div class="field"><label>Title</label><input id="pTitle" value="${esc(existing?.title||'')}" placeholder="Workout, walk, anything"></div><div class="field"><label>Optional note</label><textarea id="pNote">${esc(existing?.note||'')}</textarea></div><button class="btn blue block" id="savePlan">Save</button>`);$('#pTemplate').onchange=()=>{const t=templates.find(x=>x.id===Number($('#pTemplate').value));if(t&&!$('#pTitle').value)$('#pTitle').value=t.name};$('#savePlan').onclick=async()=>{const tid=Number($('#pTemplate').value)||null,t=templates.find(x=>x.id===tid),obj={id:existing?.id,date:$('#pDate').value,templateId:tid,title:$('#pTitle').value||t?.name||'Session',kind:t?.type||'other',note:$('#pNote').value,status:existing?.status||'planned'};existing?await db.put('planned',obj):await db.add('planned',obj);closeSheet();render()}}
async function startPlanned(p){if(!p.templateId){p.status='done';await db.put('planned',p);render();return}const t=await db.get('templates',p.templateId);if(t.type==='strength')await startWorkout(t,p);else openActivity(t.type,p,t)}

async function startWorkout(template,planned=null){const [exs,phases]=await Promise.all([db.all('exercises'),db.all('phases')]);const phase=currentPhase(phases);const history=await db.all('workouts');const items=(template.items||[]).map(x=>{const e=exs.find(z=>z.id===x.exerciseId),last=findLastExercise(history,x.exerciseId);let n=phase.id==='reentry'?x.sets:(x.rehab?x.sets:(x.eventualSets||x.sets));if(phase.id==='taper')n=Math.min(n,2);const workSets=Array.from({length:n},(_,i)=>({id:uid(),type:'work',weight:last?.[i]?.weight??last?.at(-1)?.weight??x.startWeight??null,reps:null,rir:null,done:false,label:''}));return{id:uid(),exerciseId:x.exerciseId,name:e?.name||'Unknown',rest:x.rest||e?.defaultRest||90,note:x.note||'',optional:x.optional,templateConfig:structuredClone(x),last,sets:[...(x.warmups||[]).map(w=>({id:uid(),type:'warmup',weight:null,reps:null,rir:null,done:false,label:w.label||''})),...workSets]}});state.activeWorkout={templateId:template.id,templateName:template.name,plannedId:planned?.id||null,date:isoDate(),startAt:new Date().toISOString(),items,note:''};state.openExercise=0;persistActive();await renderWorkout()}
function findLastExercise(history,eid){const h=[...history].sort((a,b)=>(b.endAt||b.date).localeCompare(a.endAt||a.date));for(const w of h){const it=w.items?.find(x=>x.exerciseId===eid);if(it)return it.sets?.filter(s=>s.type==='work'&&s.reps)}return null}
function persistActive(){if(state.activeWorkout)localStorage.setItem('slopeActiveWorkout',JSON.stringify(state.activeWorkout));else localStorage.removeItem('slopeActiveWorkout')}
async function renderWorkout(){const w=state.activeWorkout;$('#app').innerHTML=`<div class="workout-head"><div class="top"><div><div class="eyebrow">Active workout</div><h1>${esc(w.templateName)}</h1><div class="small muted">Tap an exercise to expand. Tap a value and just type over it.</div></div><button class="btn small ghost" id="pauseWorkout">Close</button></div></div>${w.items.map((it,i)=>exerciseHTML(it,i)).join('')}<button class="btn secondary block" id="addWorkoutEx">+ Add exercise</button><section class="card" style="margin-top:12px"><div class="row"><div><h3>Workout note</h3><div class="small muted">Optional. Coach will see it automatically.</div></div><button class="btn small ghost" id="editWorkoutNote">${w.note?'Edit':'Add'}</button></div></section><button class="btn blue block" id="finishWorkout">Finish workout</button>`;$('#pauseWorkout').onclick=()=>{persistActive();state.activeWorkout=null;state.tab='today';render()};$('#addWorkoutEx').onclick=addWorkoutExercise;$('#editWorkoutNote').onclick=editWorkoutNote;$('#finishWorkout').onclick=finishWorkout;$$('[data-open-ex]').forEach(b=>b.onclick=()=>{state.openExercise=Number(b.dataset.openEx);renderWorkout()});$$('[data-set-field]').forEach(inp=>{selectOnFocus(inp);inp.oninput=()=>{const [i,j,f]=inp.dataset.setField.split(':');state.activeWorkout.items[i].sets[j][f]=f==='type'?inp.value:(inp.value===''?null:Number(inp.value));persistActive()}});$$('[data-set-tick]').forEach(b=>b.onclick=()=>toggleSet(Number(b.dataset.i),Number(b.dataset.j)));$$('[data-set-del]').forEach(b=>b.onclick=()=>{state.activeWorkout.items[Number(b.dataset.i)].sets.splice(Number(b.dataset.j),1);persistActive();renderWorkout()});$$('[data-add-set]').forEach(b=>b.onclick=()=>{state.activeWorkout.items[Number(b.dataset.i)].sets.push({id:uid(),type:'work',weight:null,reps:null,rir:null,done:false,label:''});persistActive();renderWorkout()});$$('[data-add-warm]').forEach(b=>b.onclick=()=>{state.activeWorkout.items[Number(b.dataset.i)].sets.unshift({id:uid(),type:'warmup',weight:null,reps:null,rir:null,done:false,label:''});persistActive();renderWorkout()});$$('[data-ex-menu]').forEach(b=>b.onclick=()=>exerciseMenu(Number(b.dataset.i)));if(state.timer)renderTimer()}
function exerciseHTML(it,i){const open=i===state.openExercise,last=it.last?.length?it.last.map(s=>`${s.weight?`${s.weight}×`:''}${s.reps}`).join(' · '):'No recent logged sets';const completed=it.sets.filter(s=>s.type==='work'&&s.done).length,work=it.sets.filter(s=>s.type==='work').length;return `<section class="exercise ${open?'open':''}"><button class="exercise-summary" data-open-ex="${i}" style="width:100%;border:0;background:transparent;text-align:left"><div class="ex-main"><div class="row" style="justify-content:flex-start;gap:7px"><h3>${esc(it.name)}</h3>${it.optional?'<span class="pill">optional</span>':''}</div><div class="ex-last">${completed?`${completed}/${work} sets · `:''}Last: ${esc(last)}</div></div><span class="chev">⌄</span></button>${open?`<div class="exercise-body"><div class="row" style="margin-bottom:8px"><div class="small muted">Rest ${it.rest}s${it.note?` · ${esc(it.note)}`:''}</div><button class="btn small ghost" data-ex-menu data-i="${i}">•••</button></div><div class="sethead"><span>#</span><span>Type</span><span>kg</span><span>reps</span><span>RIR</span><span></span></div>${it.sets.map((s,j)=>`<div class="setrow"><span class="setnum">${j+1}</span><select data-set-field="${i}:${j}:type"><option value="work" ${s.type==='work'?'selected':''}>work</option><option value="warmup" ${s.type==='warmup'?'selected':''}>warm</option></select><input data-set-field="${i}:${j}:weight" inputmode="decimal" value="${s.weight??''}" placeholder="${s.label||'—'}"><input data-set-field="${i}:${j}:reps" inputmode="numeric" value="${s.reps??''}" placeholder="—"><input data-set-field="${i}:${j}:rir" inputmode="numeric" value="${s.rir??''}" placeholder="—"><button class="tick ${s.done?'done':''}" data-set-tick data-i="${i}" data-j="${j}">${s.done?'✓':'○'}</button></div>`).join('')}<div class="wrap" style="margin-top:9px"><button class="btn small secondary" data-add-set data-i="${i}">+ set</button><button class="btn small ghost" data-add-warm data-i="${i}">+ warm-up</button></div></div>`:''}</section>`}
function toggleSet(i,j){const s=state.activeWorkout.items[i].sets[j];s.done=!s.done;if(s.done){state.timer={ends:Date.now()+state.activeWorkout.items[i].rest*1000,label:state.activeWorkout.items[i].name};startTimer()}else if(state.timer?.label===state.activeWorkout.items[i].name)clearTimer();persistActive();renderWorkout()}
function startTimer(){clearInterval(state.timerInterval);state.timerInterval=setInterval(()=>{if(!state.timer||state.timer.ends<=Date.now()){clearTimer();return}renderTimer()},1000)}
function clearTimer(){clearInterval(state.timerInterval);state.timer=null;$('#timerpill')?.remove()}
function renderTimer(){if(!state.timer)return;let left=Math.max(0,Math.ceil((state.timer.ends-Date.now())/1000)),m=Math.floor(left/60),s=left%60,el=$('#timerpill');if(!el){document.body.insertAdjacentHTML('beforeend','<div id="timerpill" class="timerpill"><span class="timer-dot"></span><strong id="timerTime"></strong><span class="tiny" id="timerLabel"></span><button id="timerAdd">+30</button><button id="timerClose">×</button></div>');$('#timerAdd').onclick=()=>{state.timer.ends+=30000;renderTimer()};$('#timerClose').onclick=clearTimer;el=$('#timerpill')}$('#timerTime').textContent=`${m}:${pad(s)}`;$('#timerLabel').textContent=state.timer.label}
async function exerciseMenu(i){const it=state.activeWorkout.items[i];showSheet(`<div class="sheethead"><div><div class="eyebrow">During workout</div><h2>${esc(it.name)}</h2></div><button class="btn small ghost" data-close>Close</button></div><div class="field"><label>Rest seconds</label><div class="input-wrap"><input id="exRest" inputmode="numeric" value="${it.rest}"><span class="suffix">sec</span></div></div><div class="field"><label>Note for today</label><textarea id="exNote">${esc(it.note||'')}</textarea></div><div class="wrap"><button class="btn blue" id="saveExSession">Save</button><button class="btn danger" id="removeExSession">Remove exercise</button></div>`);$('#saveExSession').onclick=()=>{it.rest=Number($('#exRest').value)||90;it.note=$('#exNote').value;persistActive();closeSheet();renderWorkout()};$('#removeExSession').onclick=()=>{state.activeWorkout.items.splice(i,1);state.openExercise=Math.max(0,i-1);persistActive();closeSheet();renderWorkout()}}
async function addWorkoutExercise(){const exs=await db.all('exercises');showSheet(`<div class="sheethead"><div><div class="eyebrow">Workout</div><h2>Add exercise</h2></div><button class="btn small ghost" data-close>Close</button></div><select id="newWorkoutEx">${exs.sort((a,b)=>a.name.localeCompare(b.name)).map(e=>`<option value="${e.id}">${esc(e.name)}</option>`).join('')}</select><button class="btn blue block" id="addExNow" style="margin-top:12px">Add</button>`);$('#addExNow').onclick=()=>{const e=exs.find(x=>x.id===Number($('#newWorkoutEx').value));state.activeWorkout.items.push({id:uid(),exerciseId:e.id,name:e.name,rest:e.defaultRest||90,note:'',optional:false,last:null,sets:[{id:uid(),type:'work',weight:null,reps:null,rir:null,done:false,label:''}]});state.openExercise=state.activeWorkout.items.length-1;persistActive();closeSheet();renderWorkout()}}
function editWorkoutNote(){showSheet(`<div class="sheethead"><div><div class="eyebrow">Context</div><h2>Workout note</h2></div><button class="btn small ghost" data-close>Close</button></div><textarea id="wnote" placeholder="Felt strong, legs dead from Snozone, machine setup was weird…">${esc(state.activeWorkout.note||'')}</textarea><button class="btn blue block" id="saveWnote" style="margin-top:12px">Save</button>`);$('#saveWnote').onclick=()=>{state.activeWorkout.note=$('#wnote').value.trim();persistActive();closeSheet();renderWorkout()}}
async function finishWorkout(){const w=structuredClone(state.activeWorkout);w.endAt=new Date().toISOString();w.status='complete';const id=await db.add('workouts',w);if(w.plannedId){const p=await db.get('planned',w.plannedId);if(p){p.status='done';p.workoutId=id;await db.put('planned',p)}}state.activeWorkout=null;persistActive();clearTimer();showSheet(`<div class="sheethead"><div><div class="eyebrow">Done</div><h2>${esc(w.templateName)}</h2></div><button class="btn small ghost" data-close>Close</button></div><div class="hero"><div class="eyebrow">Nice.</div><div class="count">${w.items.flatMap(x=>x.sets).filter(s=>s.type==='work'&&s.done).length} <span>working sets logged</span></div><p class="small muted">No confetti cannon. You did the workout.</p></div><button class="btn blue block" id="finishClose">Back to today</button>`);$('#finishClose').onclick=()=>{closeSheet();state.tab='today';render()}}
function openActivity(kind,planned,t){const snow=kind==='snow';showSheet(`<div class="sheethead"><div><div class="eyebrow">${snow?'Snow':'Cardio'}</div><h2>${esc(t.name)}</h2></div><button class="btn small ghost" data-close>Close</button></div><div class="grid2"><div class="field"><label>Minutes</label><div class="input-wrap"><input id="aMin" inputmode="numeric" value="${t.activity?.minutes||60}"><span class="suffix">min</span></div></div><div class="field"><label>Effort</label><div class="input-wrap"><input id="aEff" inputmode="numeric" value="${snow?6:4}"><span class="suffix">/10</span></div></div></div>${snow?`<div class="field"><label>Anything worth remembering?</label><textarea id="aNote" placeholder="Nope is a perfectly valid answer. Short turns clicked; shoulder rotation crept in at speed; instructor said…"></textarea></div><div class="field"><label>Leg fatigue</label><div class="input-wrap"><input id="aLeg" inputmode="numeric" placeholder="optional"><span class="suffix">/10</span></div></div>`:`<div class="field"><label>Optional note</label><textarea id="aNote"></textarea></div>`}<button class="btn blue block" id="saveActivity">Save ${snow?'ski':'cardio'} session</button>`);$('#saveActivity').onclick=async()=>{await db.add('activities',{date:isoDate(),kind:snow?'snow':'cardio',minutes:Number($('#aMin').value)||0,activity:snow?'Snozone':t.activity?.kind||t.name,effort:num($('#aEff').value),legFatigue:num($('#aLeg')?.value),note:$('#aNote').value.trim()});if(planned){planned.status='done';await db.put('planned',planned)}closeSheet();toast('Logged');render()}}

async function renderCoach(){const s=await getSettings(),thread=await getCoachThread(),ws=isoDate(monday()),review=(await db.all('weeklyReviews')).find(r=>r.weekStart===ws);const mem=s.coachMemory||{};const quote=review?.coachResponse||thread.messages?.filter(m=>m.role==='assistant').at(-1)?.content||'Build the routine before you build the load.';$('#app').innerHTML=`<div class="top"><div><div class="eyebrow">Not a dashboard</div><h1>Coach</h1><div class="muted small">The numbers are evidence. This is the judgement bit.</div></div><span class="pill ${localStorage.getItem('openaiKey')?'good':'warn'}">${localStorage.getItem('openaiKey')?'AI connected':'AI off'}</span></div><section class="coach-hero"><div class="eyebrow">Right now</div><div class="coach-quote">“${esc(firstParagraph(quote))}”</div><div class="watchlist">${[...(mem.watch||[]),...(mem.testing||[])].slice(0,4).map(x=>`<div class="watch">${esc(x)}</div>`).join('')||'<div class="watch">Get enough normal weeks logged to make useful decisions.</div>'}</div></section><div class="section"><div><h2>Check in</h2><p class="small muted">Coach already gets your logs. Add only what the data missed.</p></div></div><section class="card"><div class="row"><div><h3>${review?'This week is checked in':'How did the week feel?'}</h3><div class="small muted" style="margin-top:4px">${review?'You can reopen the conversation anytime.':'Usually one thought is enough.'}</div></div><button class="btn blue" id="weeklyCheck">${review?'Continue':'Check in'}</button></div></section><section class="card"><div class="row"><div><h3>Talk it through</h3><div class="small muted" style="margin-top:4px">Legs wrecked? Starving? Bad Snozone? Ask with your current context attached.</div></div><button class="btn secondary" id="talkCoach">Talk</button></div></section><div class="section"><div><h2>Coach memory</h2><p class="small muted">What the app carries forward between conversations.</p></div><button class="btn small ghost" id="editMemory">Edit</button></div><section class="card">${memoryHTML(mem)}</section>`;$('#weeklyCheck').onclick=()=>startWeeklyCheckIn(ws);$('#talkCoach').onclick=()=>openCoachChat(false);$('#editMemory').onclick=editCoachMemory}
function firstParagraph(t){return String(t||'').split(/\n\s*\n/)[0].replace(/^#+\s*/,'').slice(0,300)}
function memoryHTML(m){const groups=[['Themes',m.themes],['Testing',m.testing],['Decisions',m.decisions],['Watching',m.watch]];return groups.map(([l,a])=>a?.length?`<div style="margin-bottom:12px"><div class="eyebrow" style="color:var(--sage)">${l}</div>${a.map(x=>`<div class="small" style="padding:5px 0">${esc(x)}</div>`).join('')}</div>`:'').join('')||'<div class="muted small">No meaningful patterns stored yet.</div>'}
async function editCoachMemory(){const s=await getSettings(),m=s.coachMemory||{};showSheet(`<div class="sheethead"><div><div class="eyebrow">Transparent memory</div><h2>What Coach remembers</h2></div><button class="btn small ghost" data-close>Close</button></div><p class="small muted">One item per line. You can edit or delete anything the coach has inferred.</p>${memoryField('Themes','memThemes',m.themes)}${memoryField('Things we’re testing','memTesting',m.testing)}${memoryField('Decisions','memDecisions',m.decisions)}${memoryField('Things to watch','memWatch',m.watch)}<button class="btn blue block" id="saveMemory">Save memory</button>`);$('#saveMemory').onclick=async()=>{const lines=id=>$('#'+id).value.split('\n').map(x=>x.trim()).filter(Boolean);await saveSettings({coachMemory:{themes:lines('memThemes'),testing:lines('memTesting'),decisions:lines('memDecisions'),watch:lines('memWatch')}});closeSheet();render()}}
function memoryField(label,id,a){return `<div class="field"><label>${label}</label><textarea id="${id}">${esc((a||[]).join('\n'))}</textarea></div>`}
async function startWeeklyCheckIn(ws){const existing=(await db.all('weeklyReviews')).find(r=>r.weekStart===ws);if(existing){openCoachChat(true,ws);return}showSheet(`<div class="sheethead"><div><div class="eyebrow">w/c ${fmt(ws)}</div><h2>Check in</h2></div><button class="btn small ghost" data-close>Close</button></div><p class="small muted">I already have your weight, food summaries, steps, planned/completed sessions, workout detail, Snozone/cardio logs and any notes you wrote during the week.</p><div class="field"><label>How did the week feel?</label><div class="moods" id="moods">${['Great','Good','Okay','Rough','Awful'].map(x=>`<button class="mood" data-mood="${x}">${x}</button>`).join('')}</div></div><div class="field"><label>Anything the logs won’t tell me? <span class="muted">Optional.</span></label><textarea id="weekContext" placeholder="Work was chaos. Dinner out Saturday wasn’t tracked. I’m ridiculously hungry. Or just leave this blank."></textarea></div><button class="btn blue block" id="beginCheck">Talk it through</button>`);let mood='Okay';$$('[data-mood]').forEach(b=>b.onclick=()=>{$$('[data-mood]').forEach(x=>x.classList.remove('on'));b.classList.add('on');mood=b.dataset.mood});$$('[data-mood]')[2]?.classList.add('on');$('#beginCheck').onclick=async()=>{const context=$('#weekContext').value.trim();await db.add('weeklyReviews',{weekStart:ws,createdDate:isoDate(),mood,context,coachResponse:''});closeSheet();await openCoachChat(true,ws,{mood,context,initial:true})}}
async function getCoachThread(){let xs=(await db.all('aiReviews')).filter(x=>x.kind==='coachThread').sort((a,b)=>(b.updatedAt||'').localeCompare(a.updatedAt||''));if(xs[0])return xs[0];const id=await db.add('aiReviews',{kind:'coachThread',updatedAt:new Date().toISOString(),messages:[]});return await db.get('aiReviews',id)}
async function openCoachChat(isWeekly=false,ws=isoDate(monday()),opts={}){if(!localStorage.getItem('openaiKey')){toast('Connect AI in More first');return}const thread=await getCoachThread();showSheet(`<div class="sheethead"><div><div class="eyebrow">${isWeekly?'Weekly check-in':'Coach'}</div><h2>${isWeekly?`w/c ${fmt(ws)}`:'Talk it through'}</h2></div><button class="btn small ghost" data-close>Close</button></div><div class="chat" id="chat">${thread.messages.slice(-12).map(m=>`<div class="msg ${m.role}">${esc(m.content)}</div>`).join('')}</div><div class="composer"><div class="composer-row"><textarea id="coachInput" placeholder="Say what’s on your mind…"></textarea><button class="btn blue" id="sendCoach">↑</button></div></div>`,{full:true});const chat=$('#chat');chat.scrollTop=chat.scrollHeight;$('#sendCoach').onclick=()=>sendCoachMessage(isWeekly,ws);$('#coachInput').addEventListener('keydown',e=>{if(e.key==='Enter'&&!e.shiftKey){e.preventDefault();sendCoachMessage(isWeekly,ws)}});if(opts.initial){const hidden=`WEEKLY CHECK-IN START. Mood: ${opts.mood}. Extra context: ${opts.context||'none'}. Review the week context you have been given. Do not recite the dashboard. If one or two missing facts would materially change your judgement, ask concise questions. Otherwise give your coaching take and how to approach next week.`;await sendCoachMessage(true,ws,hidden,true)}}
async function sendCoachMessage(isWeekly,ws,override=null,hiddenUser=false){const inp=$('#coachInput'),text=override||inp?.value.trim();if(!text)return;if(inp)inp.value='';const thread=await getCoachThread();thread.messages.push({role:'user',content:text,hidden:hiddenUser,at:new Date().toISOString()});if(!hiddenUser)$('#chat')?.insertAdjacentHTML('beforeend',`<div class="msg user">${esc(text)}</div>`);$('#chat')?.insertAdjacentHTML('beforeend','<div class="msg assistant" id="thinking">Thinking…</div>');try{const prompt=await coachPrompt(thread.messages,isWeekly,ws);const raw=await callOpenAI(prompt);const {reply,memory}=parseCoachReply(raw);$('#thinking')?.remove();$('#chat')?.insertAdjacentHTML('beforeend',`<div class="msg assistant">${esc(reply)}</div>`);thread.messages.push({role:'assistant',content:reply,at:new Date().toISOString()});thread.messages=thread.messages.slice(-30);thread.updatedAt=new Date().toISOString();await db.put('aiReviews',thread);if(memory)await saveSettings({coachMemory:memory});if(isWeekly){let review=(await db.all('weeklyReviews')).find(r=>r.weekStart===ws);if(review){review.coachResponse=reply;review.updatedAt=isoDate();await db.put('weeklyReviews',review)}}const chat=$('#chat');if(chat)chat.scrollTop=chat.scrollHeight}catch(e){$('#thinking')?.remove();$('#chat')?.insertAdjacentHTML('beforeend',`<div class="msg assistant">I couldn't reach the coach: ${esc(friendlyAIError(e))}</div>`)}}
async function coachPrompt(messages,isWeekly,ws){const [s,phases,goals,reviews]=await Promise.all([getSettings(),db.all('phases'),db.all('goals'),db.all('weeklyReviews')]);const phase=currentPhase(phases),context=await compileCoachContext(ws),memory=s.coachMemory||{},review=reviews.find(r=>r.weekStart===ws);return `You are the long-term personal training, ski-preparation and practical life coach inside Gareth's private app.

MODE
${isWeekly?'WEEKLY CHECK-IN':'OPEN COACH CONVERSATION'}${review?`
Weekly mood: ${review.mood||'not stated'}
Extra context supplied at check-in: ${review.context||'none'}`:''}

ROLE AND TONE
You are a partner, not a calculator or compliance bot. Gareth can read his own numbers. Use data as evidence only when it changes the judgement. Be warm, grounded and conversational without fake enthusiasm. Credit things that are genuinely earned. Challenge excuses or repeated avoidance when evidence supports it, but never shame. Sometimes the right answer is "do less". Sometimes it is "you are taking the piss; do the session." Distinguish a hard week, poor adherence, bad planning and bad luck.

GOALS
- Arrive at Les Carroz on 9 Jan 2027 lighter, stronger, fitter and skiing better.
- Keep a recognisable full-body A/B strength programme while ski specificity rises gradually.
- Use Les Carroz as evidence for the Flaine build to 27 Mar 2027.
- Build routines that survive work, social life, holidays and Christmas rather than demanding perfection.

CURRENT PHASE
${phase.name}: ${phase.summary}
Rules: ${(phase.rules||[]).join('; ')}

CURRENT TARGETS
Calories ${s.calorieLow}-${s.calorieHigh}; external ParrotPal target ${s.externalCalories}. Protein floor ${s.proteinFloor}g, preferred ${s.proteinPreferred}g. Steps ${s.stepTarget}/day.

COACH MEMORY
${JSON.stringify(memory,null,2)}

AUTOMATIC CONTEXT FOR THIS WEEK
${JSON.stringify(context,null,2)}

RECENT CONVERSATION
${messages.slice(-12).filter(m=>!m.hidden).map(m=>`${m.role.toUpperCase()}: ${m.content}`).join('\n')}

INSTRUCTIONS
- Do not make Gareth repeat anything already present in automatic context or recent conversation.
- If a missing fact would materially change your advice, ask at most one or two targeted questions. Do not questionnaire him.
- If you have enough context, give a human coaching response. Focus on what the week means and what to do next, not a statistical report.
- Be conservative about changing calories or training based on one noisy week.
- Daily notes, workout notes and Snozone notes are real context. Use them.
- Injury: you can reason about load and avoiding aggravation, but do not diagnose. Persistent/worsening/significant symptoms warrant appropriate professional assessment.
- If this is a weekly check-in, leave Gareth with a simple approach to next week.
- Keep replies usually 2-6 short paragraphs, not a rigid report or giant bullet list.

At the very end append exactly one machine-readable block, which is hidden from the user:
<<<MEMORY_JSON>>>{"themes":[],"testing":[],"decisions":[],"watch":[]}<<<END_MEMORY>>>
Populate it with a concise updated memory. Preserve useful existing memories unless superseded. Do not include transient trivia.

Respond now.`}
async function compileCoachContext(ws){const start=parseDate(ws),end=addDays(start,6),a=isoDate(start),b=isoDate(end);const [daily,planned,workouts,acts,reviews]=await Promise.all([db.all('daily'),db.all('planned'),db.all('workouts'),db.all('activities'),db.all('weeklyReviews')]);const ds=daily.filter(x=>x.date>=a&&x.date<=b),ps=planned.filter(x=>x.date>=a&&x.date<=b),ww=workouts.filter(x=>x.date>=a&&x.date<=b),aa=acts.filter(x=>x.date>=a&&x.date<=b);const prev=reviews.filter(r=>r.weekStart<a).sort((x,y)=>y.weekStart.localeCompare(x.weekStart)).slice(0,3).map(r=>({weekStart:r.weekStart,mood:r.mood,context:r.context,coachResponse:r.coachResponse}));return{period:{from:a,to:b},daily:ds.map(x=>({date:x.date,weight:x.weight,calories:x.calories,protein:x.protein,steps:x.steps,note:x.note})),averages:{weight:avg(ds.filter(x=>x.weight).map(x=>x.weight)),calories:avg(ds.filter(x=>x.calories).map(x=>x.calories)),protein:avg(ds.filter(x=>x.protein).map(x=>x.protein)),steps:avg(ds.filter(x=>x.steps).map(x=>x.steps)),loggedDays:ds.length},planned:ps.map(x=>({date:x.date,title:x.title,kind:x.kind,status:x.status,skipReason:x.skipReason,note:x.note})),workouts:ww.map(w=>({date:w.date,name:w.templateName,note:w.note,exercises:w.items?.map(it=>({name:it.name,sets:it.sets?.filter(s=>s.type==='work').map(s=>({weight:s.weight,reps:s.reps,rir:s.rir,done:s.done}))}))})),activities:aa.map(x=>({date:x.date,kind:x.kind,minutes:x.minutes,effort:x.effort,legFatigue:x.legFatigue,note:x.note})),previousReviews:prev}}
function parseCoachReply(raw){const m=raw.match(/<<<MEMORY_JSON>>>([\s\S]*?)<<<END_MEMORY>>>/);let memory=null;if(m){try{memory=JSON.parse(m[1].trim())}catch{}}return{reply:raw.replace(/<<<MEMORY_JSON>>>[\s\S]*?<<<END_MEMORY>>>/,'').trim(),memory}}
function friendlyAIError(e){const s=String(e.message||e);if(/401|invalid_api_key/i.test(s))return'API key rejected. Replace it in More → AI Coach.';if(/429|quota|billing/i.test(s))return'API quota/billing limit reached.';if(/model/i.test(s))return'The selected model is not available to this API project.';return s.slice(0,220)}
async function callOpenAI(prompt){const key=localStorage.getItem('openaiKey'),s=await getSettings();if(!key)throw new Error('No API key saved');const r=await fetch('https://api.openai.com/v1/responses',{method:'POST',headers:{'Content-Type':'application/json','Authorization':'Bearer '+key},body:JSON.stringify({model:s.aiModel||'gpt-5.6',input:prompt,text:{verbosity:'medium'}})});if(!r.ok)throw new Error(`${r.status}: ${await r.text()}`);const d=await r.json();return d.output_text||(d.output||[]).flatMap(o=>o.content||[]).map(c=>c.text||'').join('\n')}

async function renderProgress(){const [daily,workouts,acts,goals]=await Promise.all([db.all('daily'),db.all('workouts'),db.all('activities'),db.all('goals')]);const weights=daily.filter(x=>x.weight).sort((a,b)=>a.date.localeCompare(b.date)),trend=weightTrend(weights),tdee=estimateTDEE(daily),gs=[...goals].sort((a,b)=>a.date.localeCompare(b.date));$('#app').innerHTML=`<div class="top"><div><div class="eyebrow">Long game</div><h1>Progress</h1><div class="muted small">Enough data to steer, not enough to obsess.</div></div></div><section class="card"><div class="row"><div><h2>Weight</h2><div class="small muted">7-day average ${trend.avg7?trend.avg7.toFixed(1)+' kg':'—'}</div></div><strong>${trend.rate!=null?`${trend.rate>0?'+':''}${trend.rate.toFixed(2)} kg/wk`:'building trend'}</strong></div>${weightSVG(weights)}</section><div class="grid2"><section class="card"><div class="eyebrow">Observed TDEE</div><div class="count" style="font-size:29px">${tdee?Math.round(tdee):'—'} <span>kcal</span></div><div class="small muted">Shown only after enough calorie + weight data.</div></section><section class="card"><div class="eyebrow">Snow time</div><div class="count" style="font-size:29px">${acts.filter(x=>x.kind==='snow').reduce((a,x)=>a+(x.minutes||0),0)} <span>min</span></div><div class="small muted">Logged Snozone time.</div></section></div><section class="card"><h2>Trips</h2>${gs.map(g=>projectionRow(g,trend)).join('')}</section><section class="card"><div class="metric-row"><span>Strength workouts logged</span><strong>${workouts.length}</strong></div><div class="metric-row"><span>Snozone sessions</span><strong>${acts.filter(x=>x.kind==='snow').length}</strong></div><div class="metric-row"><span>Cardio sessions</span><strong>${acts.filter(x=>x.kind==='cardio').length}</strong></div></section>`}
function weightTrend(weights){if(!weights.length)return{};const now=new Date(),recent=days=>weights.filter(x=>(now-parseDate(x.date))/86400000<days);const a7=avg(recent(7).map(x=>x.weight)),r28=recent(28);let rate=null;if(r28.length>=4){const n=Math.max(2,Math.floor(r28.length/3)),a=avg(r28.slice(0,n).map(x=>x.weight)),b=avg(r28.slice(-n).map(x=>x.weight)),days=(parseDate(r28.at(-1).date)-parseDate(r28[0].date))/86400000;rate=(b-a)/(Math.max(7,days)/7)}return{avg7:a7,current:weights.at(-1).weight,rate}}
function estimateTDEE(daily){const xs=daily.filter(x=>x.calories&&x.weight).sort((a,b)=>a.date.localeCompare(b.date));if(xs.length<21)return null;const r=xs.slice(-35),c=avg(r.map(x=>x.calories)),n=Math.max(3,Math.floor(r.length/4)),first=avg(r.slice(0,n).map(x=>x.weight)),last=avg(r.slice(-n).map(x=>x.weight)),days=(parseDate(r.at(-1).date)-parseDate(r[0].date))/86400000||1;return c-((last-first)/days)*7700}
function weightSVG(weights){if(weights.length<2)return'<div class="empty">Two weigh-ins are enough to start drawing the line.</div>';const p=weights.slice(-60),v=p.map(x=>x.weight),min=Math.min(...v)-.4,max=Math.max(...v)+.4,w=600,h=140,pad=8,pts=p.map((x,i)=>`${pad+i*(w-2*pad)/(p.length-1)},${h-pad-(x.weight-min)*(h-2*pad)/(max-min)}`).join(' ');return `<svg class="spark" viewBox="0 0 ${w} ${h}" preserveAspectRatio="none"><polyline points="${pts}" fill="none" stroke="#4f78b8" stroke-width="4" stroke-linecap="round" stroke-linejoin="round"/></svg>`}
function projectionRow(g,t){if(!t.current)return`<div class="metric-row"><span>${esc(g.name)} · ${fmt(g.date)}</span><strong>—</strong></div>`;let r=t.rate??-.45,days=Math.max(0,daysUntil(g.date)),maintenance=0;if(parseDate(g.date)>parseDate('2026-12-21')&&new Date()<parseDate('2027-01-01')){const a=new Date()>parseDate('2026-12-21')?new Date():parseDate('2026-12-21'),b=parseDate(g.date)<parseDate('2027-01-01')?parseDate(g.date):parseDate('2027-01-01');maintenance=Math.max(0,(b-a)/86400000)}const proj=t.current+r*((days-maintenance)/7);return`<div class="metric-row"><div><strong>${esc(g.name)}</strong><div class="tiny muted">${fmt(g.date)}</div></div><div style="text-align:right"><strong>${proj.toFixed(1)} kg</strong><div class="tiny muted">current trajectory</div></div></div>`}

async function renderMore(){const [s,phases,templates,exs]=await Promise.all([getSettings(),db.all('phases'),db.all('templates'),db.all('exercises')]);const phase=currentPhase(phases);$('#app').innerHTML=`<div class="top"><div><div class="eyebrow">Under the bonnet</div><h1>More</h1></div></div><section class="card" id="birdPlan"><div class="row"><div><h3>Bird’s-eye plan</h3><div class="small muted" style="margin-top:4px">Current: ${esc(phase.name)} · every phase visible now</div></div><strong>›</strong></div></section><section class="card" id="templatesBtn"><div class="row"><div><h3>Templates & exercises</h3><div class="small muted" style="margin-top:4px">${templates.length} templates · ${exs.length} exercises · fully editable</div></div><strong>›</strong></div></section><section class="card" id="targetsBtn"><div class="row"><div><h3>Targets</h3><div class="small muted" style="margin-top:4px">${s.calorieLow}–${s.calorieHigh} kcal · ${s.proteinFloor}g protein floor · ${s.stepTarget.toLocaleString()} steps</div></div><strong>›</strong></div></section><section class="card" id="aiSettings"><div class="row"><div><h3>AI Coach</h3><div class="small muted" style="margin-top:4px">${localStorage.getItem('openaiKey')?'Connected locally':'Not connected'} · ${esc(s.aiModel||'gpt-5.6')}</div></div><strong>›</strong></div></section><section class="card"><div class="row"><div><h3>Backup</h3><div class="small muted" style="margin-top:4px">Export local data. API key is never included.</div></div></div><div class="wrap" style="margin-top:12px"><button class="btn secondary" id="exportBtn">Export JSON</button><label class="btn secondary" style="margin:0">Restore<input id="restoreFile" type="file" accept=".json" hidden></label></div></section><div class="tiny muted" style="text-align:center;margin-top:20px">Slope v${VERSION}</div>`;$('#birdPlan').onclick=()=>openBird(phases);$('#templatesBtn').onclick=openTemplateLibrary;$('#targetsBtn').onclick=()=>openTargets(s);$('#aiSettings').onclick=()=>openAISettings(s);$('#exportBtn').onclick=exportData;$('#restoreFile').onchange=restoreData}
function openBird(phases){const cur=currentPhase(phases);showSheet(`<div class="sheethead"><div><div class="eyebrow">Now → Flaine</div><h2>The whole plan</h2></div><button class="btn small ghost" data-close>Close</button></div>${[...phases].filter(p=>p.from).sort((a,b)=>a.from.localeCompare(b.from)).map(p=>`<div class="phase ${p.id===cur.id?'current':''}"><h3>${esc(p.name)}</h3><div class="tiny muted">${fmt(p.from)} → ${fmt(p.to)}</div><p class="small">${esc(p.summary)}</p><div class="tiny muted">${(p.rules||[]).map(esc).join(' · ')}</div></div>`).join('')}`,{full:true})}
async function openTemplateLibrary(){const ts=await db.all('templates');showSheet(`<div class="sheethead"><div><div class="eyebrow">Training machinery</div><h2>Templates</h2></div><button class="btn small ghost" data-close>Close</button></div>${ts.map(t=>`<section class="card"><div class="row"><div><h3>${esc(t.name)}</h3><div class="small muted">${esc(t.description||t.type)}</div></div><button class="btn small blue" data-template-start="${t.id}">Start</button></div><div class="wrap" style="margin-top:10px"><button class="btn small secondary" data-template-edit="${t.id}">Edit</button><button class="btn small ghost" data-template-copy="${t.id}">Duplicate</button><button class="btn small danger" data-template-del="${t.id}">Delete</button></div></section>`).join('')}<button class="btn blue block" id="newTemplate">+ New template</button><button class="btn secondary block" id="exerciseLib" style="margin-top:9px">Exercise library</button>`,{full:true});$$('[data-template-start]').forEach(b=>b.onclick=async()=>{const t=await db.get('templates',Number(b.dataset.templateStart));closeSheet();if(t.type==='strength')startWorkout(t);else openActivity(t.type,null,t)});$$('[data-template-edit]').forEach(b=>b.onclick=async()=>editTemplate(await db.get('templates',Number(b.dataset.templateEdit))));$$('[data-template-copy]').forEach(b=>b.onclick=async()=>{const t=structuredClone(await db.get('templates',Number(b.dataset.templateCopy)));delete t.id;t.name+=' copy';await db.add('templates',t);openTemplateLibrary()});$$('[data-template-del]').forEach(b=>b.onclick=async()=>{if(confirm('Delete template? Historical logs stay intact.')){await db.del('templates',Number(b.dataset.templateDel));openTemplateLibrary()}});$('#newTemplate').onclick=()=>editTemplate();$('#exerciseLib').onclick=openExerciseLibrary}
async function editTemplate(t=null){const exs=await db.all('exercises'),d=t?structuredClone(t):{name:'New template',type:'strength',description:'',items:[]};showSheet(`<div class="sheethead"><div><div class="eyebrow">Template</div><h2>${esc(d.name)}</h2></div><button class="btn small ghost" data-close>Close</button></div><div class="field"><label>Name</label><input id="teName" value="${esc(d.name)}"></div><div class="field"><label>Description</label><input id="teDesc" value="${esc(d.description||'')}"></div>${d.type==='strength'?`${d.items.map((x,i)=>{const e=exs.find(z=>z.id===x.exerciseId);return`<section class="card teitem"><div class="row"><strong>${esc(e?.name||'Unknown')}</strong><button class="btn small danger" data-te-del="${i}">×</button></div><div class="grid4" style="margin-top:10px">${tplField('Sets','sets',x.sets,i)}${tplField('Rep min','repMin',x.repMin,i)}${tplField('Rep max','repMax',x.repMax,i)}${tplField('Target','target',x.target,i)}${tplField('Rest','rest',x.rest,i)}${tplField('Start kg','startWeight',x.startWeight,i)}${tplField('Later sets','eventualSets',x.eventualSets,i)}</div><div class="field"><label>Note</label><input data-tpl="${i}:note" value="${esc(x.note||'')}"></div></section>`}).join('')}<div class="row"><select id="tplAddEx"><option value="">Add exercise…</option>${exs.map(e=>`<option value="${e.id}">${esc(e.name)}</option>`).join('')}</select><button class="btn small blue" id="tplAdd">Add</button></div>`:`<p class="muted">Activity template editing is intentionally simple in this build.</p>`}<button class="btn blue block" id="saveTemplate" style="margin-top:14px">Save template</button>`,{full:true});function capture(){d.name=$('#teName').value;d.description=$('#teDesc').value;if(d.type==='strength')$$('[data-tpl]').forEach(el=>{const [i,f]=el.dataset.tpl.split(':');d.items[Number(i)][f]=f==='note'?el.value:Number(el.value)})}$$('[data-te-del]').forEach(b=>b.onclick=()=>{capture();d.items.splice(Number(b.dataset.teDel),1);closeSheet();editTemplate(d)});$('#tplAdd')?.addEventListener('click',()=>{capture();const eid=Number($('#tplAddEx').value);if(eid){const e=exs.find(x=>x.id===eid);d.items.push({exerciseId:eid,sets:2,repMin:8,repMax:12,target:8,rest:e.defaultRest||90,startWeight:0,eventualSets:3,optional:false,rehab:false,note:'',warmups:[],progression:'double'});closeSheet();editTemplate(d)}});$('#saveTemplate').onclick=async()=>{capture();if(d.id)await db.put('templates',d);else await db.add('templates',d);closeSheet();openTemplateLibrary()}}
function tplField(label,f,v,i){return`<div class="field"><label>${label}</label><input data-tpl="${i}:${f}" inputmode="decimal" value="${v??''}"></div>`}
async function openExerciseLibrary(){const exs=await db.all('exercises');showSheet(`<div class="sheethead"><div><div class="eyebrow">Library</div><h2>Exercises</h2></div><button class="btn small ghost" data-close>Close</button></div>${exs.sort((a,b)=>a.name.localeCompare(b.name)).map(e=>`<div class="card-flat"><div class="row"><div><strong>${esc(e.name)}</strong><div class="tiny muted">${esc(e.category)} · ${esc(e.equipment)}</div></div><button class="btn small ghost" data-ex-edit="${e.id}">Edit</button></div></div>`).join('')}<button class="btn blue block" id="newExercise">+ New exercise</button>`,{full:true});$$('[data-ex-edit]').forEach(b=>b.onclick=async()=>editExercise(await db.get('exercises',Number(b.dataset.exEdit))));$('#newExercise').onclick=()=>editExercise()}
async function editExercise(e=null){showSheet(`<div class="sheethead"><div><div class="eyebrow">Exercise</div><h2>${e?'Edit':'New'}</h2></div><button class="btn small ghost" data-close>Close</button></div>${simpleField('Name','exName',e?.name||'')}${simpleField('Category','exCat',e?.category||'')}${simpleField('Equipment','exEquip',e?.equipment||'')}${simpleField('Increment','exInc',e?.increment??2.5,'decimal')}${simpleField('Default rest','exRest',e?.defaultRest??90,'numeric')}<div class="field"><label>Notes</label><textarea id="exNotes">${esc(e?.notes||'')}</textarea></div><button class="btn blue block" id="saveExercise">Save</button>`);$('#saveExercise').onclick=async()=>{const o={id:e?.id,name:$('#exName').value,category:$('#exCat').value,equipment:$('#exEquip').value,loadType:e?.loadType||'kg',increment:Number($('#exInc').value)||0,defaultRest:Number($('#exRest').value)||90,notes:$('#exNotes').value};e?await db.put('exercises',o):await db.add('exercises',Object.fromEntries(Object.entries(o).filter(([k])=>k!=='id')));closeSheet();openExerciseLibrary()}}
function simpleField(label,id,v,mode='text'){return`<div class="field"><label>${label}</label><input id="${id}" ${mode!=='text'?`inputmode="${mode}"`:''} value="${esc(v)}"></div>`}
function openTargets(s){showSheet(`<div class="sheethead"><div><div class="eyebrow">ParrotPal stays the food logger</div><h2>Targets</h2></div><button class="btn small ghost" data-close>Close</button></div>${simpleField('Calories low','calLow',s.calorieLow,'numeric')}${simpleField('Calories high','calHigh',s.calorieHigh,'numeric')}${simpleField('Current ParrotPal calorie target','extCal',s.externalCalories,'numeric')}${simpleField('Protein floor','proFloor',s.proteinFloor,'numeric')}${simpleField('Preferred protein','proPref',s.proteinPreferred,'numeric')}${simpleField('Steps/day','stepsTarget',s.stepTarget,'numeric')}<button class="btn blue block" id="saveTargets">Save</button>`);$('#saveTargets').onclick=async()=>{await saveSettings({calorieLow:Number($('#calLow').value),calorieHigh:Number($('#calHigh').value),externalCalories:Number($('#extCal').value),proteinFloor:Number($('#proFloor').value),proteinPreferred:Number($('#proPref').value),stepTarget:Number($('#stepsTarget').value)});closeSheet();render()}}
function openAISettings(s){const has=!!localStorage.getItem('openaiKey');showSheet(`<div class="sheethead"><div><div class="eyebrow">Local AI</div><h2>Coach connection</h2></div><button class="btn small ghost" data-close>Close</button></div><div class="card" style="background:var(--amber-soft)"><p class="small" style="margin:0">The key lives only in this browser/device and is excluded from backup. Use a dedicated API project/key with a low spend limit.</p></div><div class="field"><label>API key</label><input id="apiKey" type="password" value="${has?'••••••••••••••••••••':''}" placeholder="sk-..."></div><div class="field"><label>Model</label><input id="aiModel" value="${esc(s.aiModel||'gpt-5.6')}"></div><div class="wrap"><button class="btn blue" id="saveAI">Save locally</button><button class="btn secondary" id="testAI">Test</button>${has?'<button class="btn danger" id="removeAI">Remove</button>':''}</div><div id="aiStatus" class="small muted" style="margin-top:12px"></div>`);$('#saveAI').onclick=async()=>{const v=$('#apiKey').value;if(v&&!v.includes('•'))localStorage.setItem('openaiKey',v.trim());await saveSettings({aiModel:$('#aiModel').value.trim()||'gpt-5.6'});$('#aiStatus').textContent='Saved locally.'};$('#testAI').onclick=async()=>{const st=$('#aiStatus');st.textContent='Testing…';try{const out=await callOpenAI('Reply with exactly: connection works.');st.textContent=out.trim()}catch(e){st.textContent=friendlyAIError(e)}};$('#removeAI')?.addEventListener('click',()=>{localStorage.removeItem('openaiKey');closeSheet();render()})}
async function exportData(){const out={version:VERSION,exportedAt:new Date().toISOString(),stores:{}};for(const n of STORE_NAMES)out.stores[n]=await db.all(n);const blob=new Blob([JSON.stringify(out,null,2)],{type:'application/json'}),url=URL.createObjectURL(blob),a=document.createElement('a');a.href=url;a.download=`slope-backup-${isoDate()}.json`;a.click();URL.revokeObjectURL(url)}
async function restoreData(e){const f=e.target.files[0];if(!f)return;const data=JSON.parse(await f.text());if(!confirm('Replace current local data with this backup?'))return;for(const [n,xs] of Object.entries(data.stores||{})){if(!db.db.objectStoreNames.contains(n))continue;await db.clear(n);for(const x of xs){const c=structuredClone(x);await db.put(n,c)}}toast('Restored');render()}

(async()=>{await db.init();await seed();const active=localStorage.getItem('slopeActiveWorkout');if(active){try{state.activeWorkout=JSON.parse(active)}catch{}}if('serviceWorker'in navigator)navigator.serviceWorker.register('./sw.js');render()})();
